[project]
name = "one-shot-random-access"
version = "2.0.0"
description = "One-Shot Random Access"
readme = "README.md"
requires-python = "==3.13.9"
dependencies = [
    "numpy==2.3.5",
    "matplotlib==3.10.7",
    "tqdm==4.67.1",
    "pyyaml==6.0.3",
    "psutil>=6.1.1",
]
